### ISSUE TITLE
Locations gone

### ISSUE THREAD

**Issue by eldooned** [felipefrancisco/pokemon-go-map#22]
I added quite a few locations to Sheffield, UK a few days ago, looked today to see if anyone else has added any, but all my locations have gone and there is nothing in the city. Any idea what is causing this or have my requests been removed?

**Comment by felipefrancisco** [comment]
@eldooned Yesterday the database was failing lots of times due to the crazy amount of people using the map. I was forced to stop the database and migrate a backup to a better server, during this process some hundred markers, locations, reports and sights were lost, I'm really sorry about that.

Do you mind adding them again to the map? There'll be no more database related problems, I can guarantee that now.

**Comment by eldooned** [comment]
No problem at all, I'll get them all added back on now.
